FROM golang:1.22.4-alpine3.20

WORKDIR /app

# Needed in test
RUN apk update && \
    apk add gcc && \
    apk add musl-dev

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

EXPOSE 8080

RUN go install github.com/cosmtrek/air@v1.49.0
CMD ["air"]
