FROM golang:1.19.1-alpine3.16

WORKDIR /app

# Needed in test
RUN apk update && \
    apk add gcc && \
    apk add musl-dev

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

EXPOSE 8080

RUN go install github.com/cosmtrek/air@latest
CMD ["air"]
