import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Sender.module.css'

const Sender: NextPage = () => {
  return (
    <div>
      <Head>
        <title>homecam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Sender
      <div>
        <video id="localVideo" className={styles.videoBox} muted autoPlay playsInline></video>
      </div>
    </div>
  )
}

(async function(){
  if(typeof window === 'undefined') {
    return // Server sideでは実行しない
  }
  // カメラ映像取得
  const localMediaStream = await navigator.mediaDevices.getUserMedia({
    video: {
      width: { ideal: 1280 },
      height: { ideal: 720 },
      frameRate: { ideal: 8 }
    },
    audio: false
  }) as MediaStream
  const localVideo = document.getElementById('localVideo') as HTMLVideoElement
  if(localVideo !== null) {
    localVideo.srcObject = localMediaStream
  }
})()

export default Sender
